"""add planted_date to plants

Revision ID: 0687741f7467
Revises: 4de505ef83e3
Create Date: 2023-12-12 13:07:51.181753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0687741f7467'
down_revision: Union[str, None] = '4de505ef83e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('planted_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'planted_date')
    # ### end Alembic commands ###
