"""rename EC column, a few other tweaks

Revision ID: 2212c98c2d64
Revises: cf92ccc2aca9
Create Date: 2023-12-01 13:50:08.235153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2212c98c2d64'
down_revision: Union[str, None] = 'cf92ccc2aca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hydroponic_conditions', sa.Column('electrical_conductivity_ms_cm', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.alter_column('hydroponic_conditions', 'water_temperature_f',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=3, scale=2),
               existing_nullable=True)
    op.drop_column('hydroponic_conditions', 'electrical_conductivity')
    op.alter_column('taste_test', 'taste',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('taste_test', 'texture',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('taste_test', 'appearance',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('yield', sa.Column('comments', sa.Text(), nullable=True))
    op.drop_column('yield', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yield', sa.Column('notes', mysql.TEXT(), nullable=True))
    op.drop_column('yield', 'comments')
    op.alter_column('taste_test', 'appearance',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('taste_test', 'texture',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('taste_test', 'taste',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('hydroponic_conditions', sa.Column('electrical_conductivity', mysql.DECIMAL(precision=5, scale=2), nullable=True))
    op.alter_column('hydroponic_conditions', 'water_temperature_f',
               existing_type=sa.DECIMAL(precision=3, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_column('hydroponic_conditions', 'electrical_conductivity_ms_cm')
    # ### end Alembic commands ###
