"""fix associative table

Revision ID: 29d7c4c00157
Revises: 3e8654308e4b
Create Date: 2023-11-19 15:58:38.382661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '29d7c4c00157'
down_revision: Union[str, None] = '3e8654308e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plant_crosses_ibfk_2', 'plant_crosses', type_='foreignkey')
    op.drop_constraint('plant_crosses_ibfk_1', 'plant_crosses', type_='foreignkey')
    op.drop_column('plant_crosses', 'parent_1_id')
    op.drop_column('plant_crosses', 'parent_2_id')
    op.add_column('plant_plant_cross', sa.Column('role', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant_plant_cross', 'role')
    op.add_column('plant_crosses', sa.Column('parent_2_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plant_crosses', sa.Column('parent_1_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('plant_crosses_ibfk_1', 'plant_crosses', 'plants', ['parent_1_id'], ['plant_id'])
    op.create_foreign_key('plant_crosses_ibfk_2', 'plant_crosses', 'plants', ['parent_2_id'], ['plant_id'])
    # ### end Alembic commands ###
