"""try to un-break things

Revision ID: 2c868bdfc5b2
Revises: 37cc1622dac5
Create Date: 2023-11-17 11:34:59.952731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c868bdfc5b2'
down_revision: Union[str, None] = '37cc1622dac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_crosses', 'cross_date',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_crosses', 'cross_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
