"""try to break things

Revision ID: 37cc1622dac5
Revises: 74119be7ab39
Create Date: 2023-11-17 11:32:46.027573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cc1622dac5'
down_revision: Union[str, None] = '74119be7ab39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_crosses', 'cross_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_crosses', 'cross_date',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
