"""nullable germination_id for plants

Revision ID: 4de505ef83e3
Revises: 5c10ca4cd678
Create Date: 2023-12-12 13:04:55.748195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de505ef83e3'
down_revision: Union[str, None] = '5c10ca4cd678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
