"""add heirloom column

Revision ID: 5c10ca4cd678
Revises: a3ae6f863184
Create Date: 2023-12-11 15:40:34.225503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c10ca4cd678'
down_revision: Union[str, None] = 'a3ae6f863184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('heirloom', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'heirloom')
    # ### end Alembic commands ###
