"""add height_cm, leaf_count, color, texture to observation, tweak yield

Revision ID: 74119be7ab39
Revises: 8b773ff3dbfa
Create Date: 2023-11-17 10:14:54.622749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '74119be7ab39'
down_revision: Union[str, None] = '8b773ff3dbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('height_cm', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('observations', sa.Column('leaf_count', sa.Integer(), nullable=True))
    op.drop_column('yield', 'height_cm')
    op.drop_column('yield', 'leaf_count')
    op.drop_column('yield', 'nutrient_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yield', sa.Column('nutrient_level', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('yield', sa.Column('leaf_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('yield', sa.Column('height_cm', mysql.DECIMAL(precision=5, scale=2), nullable=True))
    op.drop_column('observations', 'leaf_count')
    op.drop_column('observations', 'height_cm')
    # ### end Alembic commands ###
