"""move species and variety to seed

Revision ID: 8b773ff3dbfa
Revises: c2cf0b6ddbd7
Create Date: 2023-11-17 10:12:32.209872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b773ff3dbfa'
down_revision: Union[str, None] = 'c2cf0b6ddbd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('photo', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'photo')
    # ### end Alembic commands ###
