"""major refactor

Revision ID: 8f44068df7f1
Revises: 9292eda624de
Create Date: 2023-11-19 14:46:21.195647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f44068df7f1'
down_revision: Union[str, None] = '9292eda624de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('germination',
    sa.Column('germination_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seed_id', sa.Integer(), nullable=True),
    sa.Column('planted_date', sa.Date(), nullable=True),
    sa.Column('germination_date', sa.Date(), nullable=True),
    sa.Column('seeds_attempted', sa.Integer(), nullable=True),
    sa.Column('seeds_successful', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['seed_id'], ['seeds.seed_id'], ),
    sa.PrimaryKeyConstraint('germination_id')
    )
    op.create_table('plant_plant_cross',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('cross_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cross_id'], ['plant_crosses.cross_id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.plant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('seed_cross')
    op.drop_column('hydroponic_conditions', 'tds')
    op.add_column('plants', sa.Column('germination_id', sa.Integer(), nullable=True))
    op.add_column('plants', sa.Column('system_id', sa.Integer(), nullable=True))
    op.drop_constraint('plants_ibfk_1', 'plants', type_='foreignkey')
    op.drop_constraint('plants_ibfk_2', 'plants', type_='foreignkey')
    op.create_foreign_key(None, 'plants', 'hydroponic_system', ['system_id'], ['system_id'])
    op.create_foreign_key(None, 'plants', 'germination', ['germination_id'], ['germination_id'])
    op.drop_column('plants', 'germination_date')
    op.drop_column('plants', 'hydroponic_system_id')
    op.drop_column('plants', 'seed_id')
    op.add_column('seeds', sa.Column('yield_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'seeds', 'yield', ['yield_id'], ['yield_id'])
    op.add_column('yield', sa.Column('cross_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'yield', 'plant_crosses', ['cross_id'], ['cross_id'])
    op.drop_column('yield', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yield', sa.Column('photo', sa.BLOB(), nullable=True))
    op.drop_constraint(None, 'yield', type_='foreignkey')
    op.drop_column('yield', 'cross_id')
    op.drop_constraint(None, 'seeds', type_='foreignkey')
    op.drop_column('seeds', 'yield_id')
    op.add_column('plants', sa.Column('seed_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('hydroponic_system_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('germination_date', sa.DATE(), nullable=True))
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.create_foreign_key('plants_ibfk_2', 'plants', 'seeds', ['seed_id'], ['seed_id'])
    op.create_foreign_key('plants_ibfk_1', 'plants', 'hydroponic_system', ['hydroponic_system_id'], ['system_id'])
    op.drop_column('plants', 'system_id')
    op.drop_column('plants', 'germination_id')
    op.add_column('hydroponic_conditions', sa.Column('tds', mysql.DECIMAL(precision=5, scale=2), nullable=True))
    op.create_table('seed_cross',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seed_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cross_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cross_id'], ['plant_crosses.cross_id'], name='seed_cross_ibfk_1'),
    sa.ForeignKeyConstraint(['seed_id'], ['seeds.seed_id'], name='seed_cross_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('plant_plant_cross')
    op.drop_table('germination')
    # ### end Alembic commands ###
