"""remove plant_type

Revision ID: 9292eda624de
Revises: b2ab8c0c271d
Create Date: 2023-11-17 22:52:29.996186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9292eda624de'
down_revision: Union[str, None] = 'b2ab8c0c271d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'plant_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('plant_type', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
