"""fix observations

Revision ID: bdb4c73c7e31
Revises: 2c868bdfc5b2
Create Date: 2023-11-17 12:02:09.206341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb4c73c7e31'
down_revision: Union[str, None] = '2c868bdfc5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('color', sa.String(length=255), nullable=True))
    op.add_column('observations', sa.Column('texture', sa.String(length=255), nullable=True))
    op.drop_column('observations', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('photo', sa.BLOB(), nullable=True))
    op.drop_column('observations', 'texture')
    op.drop_column('observations', 'color')
    # ### end Alembic commands ###
