"""observation fields nullable

Revision ID: cb8b5d231983
Revises: 29d7c4c00157
Create Date: 2023-11-20 00:18:24.409206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8b5d231983'
down_revision: Union[str, None] = '29d7c4c00157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('germination_ibfk_1', 'germination', type_='foreignkey')
    op.create_foreign_key(None, 'germination', 'seeds', ['seed_id'], ['seed_id'])
    op.drop_constraint('hydroponic_conditions_ibfk_1', 'hydroponic_conditions', type_='foreignkey')
    op.create_foreign_key(None, 'hydroponic_conditions', 'hydroponic_system', ['system_id'], ['system_id'])
    op.drop_constraint('observations_ibfk_1', 'observations', type_='foreignkey')
    op.create_foreign_key(None, 'observations', 'plants', ['plant_id'], ['plant_id'])
    op.drop_constraint('plant_plant_cross_ibfk_1', 'plant_plant_cross', type_='foreignkey')
    op.drop_constraint('plant_plant_cross_ibfk_2', 'plant_plant_cross', type_='foreignkey')
    op.create_foreign_key(None, 'plant_plant_cross', 'plants', ['plant_id'], ['plant_id'])
    op.create_foreign_key(None, 'plant_plant_cross', 'plant_crosses', ['cross_id'], ['cross_id'])
    op.drop_constraint('plants_ibfk_1', 'plants', type_='foreignkey')
    op.drop_constraint('plants_ibfk_2', 'plants', type_='foreignkey')
    op.create_foreign_key(None, 'plants', 'hydroponic_system', ['system_id'], ['system_id'])
    op.create_foreign_key(None, 'plants', 'germination', ['germination_id'], ['germination_id'])
    op.drop_constraint('seeds_ibfk_1', 'seeds', type_='foreignkey')
    op.create_foreign_key(None, 'seeds', 'yield', ['yield_id'], ['yield_id'])
    op.drop_constraint('taste_test_ibfk_1', 'taste_test', type_='foreignkey')
    op.create_foreign_key(None, 'taste_test', 'plants', ['plant_id'], ['plant_id'])
    op.drop_constraint('yield_ibfk_2', 'yield', type_='foreignkey')
    op.drop_constraint('yield_ibfk_1', 'yield', type_='foreignkey')
    op.create_foreign_key(None, 'yield', 'plant_crosses', ['cross_id'], ['cross_id'])
    op.create_foreign_key(None, 'yield', 'plants', ['plant_id'], ['plant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yield', type_='foreignkey')
    op.drop_constraint(None, 'yield', type_='foreignkey')
    op.create_foreign_key('yield_ibfk_1', 'yield', 'plants', ['plant_id'], ['plant_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('yield_ibfk_2', 'yield', 'plant_crosses', ['cross_id'], ['cross_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'taste_test', type_='foreignkey')
    op.create_foreign_key('taste_test_ibfk_1', 'taste_test', 'plants', ['plant_id'], ['plant_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'seeds', type_='foreignkey')
    op.create_foreign_key('seeds_ibfk_1', 'seeds', 'yield', ['yield_id'], ['yield_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.create_foreign_key('plants_ibfk_2', 'plants', 'hydroponic_system', ['system_id'], ['system_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('plants_ibfk_1', 'plants', 'germination', ['germination_id'], ['germination_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'plant_plant_cross', type_='foreignkey')
    op.drop_constraint(None, 'plant_plant_cross', type_='foreignkey')
    op.create_foreign_key('plant_plant_cross_ibfk_2', 'plant_plant_cross', 'plants', ['plant_id'], ['plant_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('plant_plant_cross_ibfk_1', 'plant_plant_cross', 'plant_crosses', ['cross_id'], ['cross_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.create_foreign_key('observations_ibfk_1', 'observations', 'plants', ['plant_id'], ['plant_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'hydroponic_conditions', type_='foreignkey')
    op.create_foreign_key('hydroponic_conditions_ibfk_1', 'hydroponic_conditions', 'hydroponic_system', ['system_id'], ['system_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'germination', type_='foreignkey')
    op.create_foreign_key('germination_ibfk_1', 'germination', 'seeds', ['seed_id'], ['seed_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
