"""add death date

Revision ID: cf92ccc2aca9
Revises: 3ab1e78ce8e6
Create Date: 2023-11-21 15:31:05.583983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf92ccc2aca9'
down_revision: Union[str, None] = '3ab1e78ce8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('death_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'death_date')
    # ### end Alembic commands ###
