"""remove role from plant_plant_cross

Revision ID: f419d6b5d118
Revises: 0687741f7467
Create Date: 2024-03-02 16:50:48.493793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f419d6b5d118'
down_revision: Union[str, None] = '0687741f7467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant_plant_cross', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_plant_cross', sa.Column('role', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
